[package]
name = "alidns-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
rand = "0.8.5"
reqwest = { version = "0.12.9", features = ["json"] }
tokio = { version = "1.41.1", features = ["full"] }
